# Site settings
title: "QuarryScan"
email: 
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://quarryscan.no" # the base hostname & protocol for your site

vebjorn_email: "vebjorn@quarryscan.no"
anders_email: "anders@quarryscan.no"

# Build settings
markdown: kramdown
